Merge State Machine into Main
AgamAulakh/app_core pull request #3
Opened 2024-02-28 21:40 UTC by mkenzie-m

Merge the state machine, LED handler, and button handler firmware into main branch

2024-03-10 06:35 UTC, AgamAulakh requested changes
mostly small nitpicks!

2024-03-10 06:35 UTC, AgamAulakh commented on CMakeLists.txt
> +)
Instead of manually adding source files, I think it would be easier to recursively add them like this:

`file(GLOB_RECURSE APP_SOURCES "${CMAKE_CURRENT_SOURCE_DIR}/src/*.cpp")`
`target_sources(app PRIVATE ${APP_SOURCES})`

2024-03-10 06:35 UTC, AgamAulakh commented on inc/led_handler.h
> +void set_led_white();
Can we put these in a namespace for LED1? It seems all of the set functions are for LED1 and it would help keep the code clean:
in .h file:
```
namespace LED1 {
    const struct pwm_dt_spec red_pwm_led = PWM_DT_SPEC_GET(DT_ALIAS(redled));
    const struct pwm_dt_spec green_pwm_led = PWM_DT_SPEC_GET(DT_ALIAS(greenled));
    const struct pwm_dt_spec blue_pwm_led = PWM_DT_SPEC_GET(DT_ALIAS(blueled));

    void init() {
        ...
    }
    void set_blue() {...}
    void set_yellow() {...}
    void set_flash_green() {...}
    void set_solid_green() {...}
    void set_flash_red() {...}
    void set_solid_red();
    void set_white() {...}
};
```

that way, outside of this file, we can call these functions like LED1::set_white();

2024-03-10 06:35 UTC, AgamAulakh commented on nrf5340dk_nrf5340_cpuapp.overlay
> +		};
on my end, this block is greyed out... which I think means it's being overwritten. I don't know enough about devicetrees to figure out why 🙈 

maybe we should clean this file up before merging and I'll rebase off the new one!

2024-03-10 06:35 UTC, AgamAulakh commented on src/led_handler.cpp
> +}
I think we can transfer these function definitions into the led_handler.h file if we use the namespace idea. We should also remove the log_dbg calls if all of these functions have been tested (to decrease overhead)!

2024-03-10 06:35 UTC, AgamAulakh commented on src/state_machine.cpp
> +#define EVENT_BTN_PRESS BIT(0)
minor nitpick:
Let's move these #defines to state_machine.h.
Let's also move the includes to that header file and only include "src/state_machine.h" in this file.

2024-03-10 06:35 UTC, AgamAulakh commented on src/state_machine.cpp
> +static struct gpio_callback button_cb_data;
I think we should also protect our buttons with namespaces.

```
namespace TestButton {
    static const struct gpio_dt_spec data_enable_button = GPIO_DT_SPEC_GET_OR(DATA_ENABLE, gpios, {0});
    static struct gpio_callback button_cb_data;

    init() {...};
    button_press() {...};
}
```

2024-03-10 06:35 UTC, AgamAulakh commented on src/state_machine.cpp
> +    s_obj.events = k_event_clear(&s_obj.button_press_event, EVENT_BTN_PRESS);
maybe all clean-up can happen in state_exit() calls? Although not every state has an exit function implemented at this moment.

2024-03-10 06:35 UTC, AgamAulakh commented on src/state_machine.cpp
> +} s_obj;
Like in previous comments, I'm a bit hesitant to keep things global. Would it take long to encapsulate this in a static class?

2024-03-16 20:17 UTC, mkenzie-m commented
Changes implemented

2024-03-16 20:18 UTC, merged